config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'homes/index'
  get 'homes/second'
  post 'homes/second'
  get 'homes/third'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    order_currency = 'BTC'
    payment_currency = 'KRW'
    
    address = "https://api.bithumb.com/public/ticker/#{order_currency}_#{payment_currency}"
    response = HTTParty.get(address)
    @data = response.parsed_response["data"]
    @closing_price = @data["closing_price"]
  end

  def second
    order_currency = params[:currency_name].upcase
    payment_currency = 'KRW'
    
    address = "https://api.bithumb.com/public/ticker/#{order_currency}_#{payment_currency}"
    response = HTTParty.get(address)
    @data = response.parsed_response["data"]
    
    if order_currency != 'ALL'
      @result = {order_currency => @data}
    else
      @result = @data
    end
  end

  def third
    address = "https://api.bithumb.com/public/ticker/ALL_KRW"
    response = HTTParty.get(address)
    @data = response.parsed_response["data"]
    
    max_fluc = {}
    @data.each do |cur|
      if cur[0] != "date"
        max_fluc.store(cur[0], cur[-1]['fluctate_rate_24H'].to_i)
      end
    end
    max_fluc = max_fluc.sort {|a1,a2| a2[1] <=> a1[1]}
    @max_fluc = max_fluc.first(5)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

<%= form_tag('/homes/second') do %>
    <div>
        <%= text_field_tag 'currency_name' %>
        <%= submit_tag 'send' %>
        {order_currency} = 주문 통화(코인), ALL(전체), 기본값 : BTC
    </div>
<% end %>
<hr>
<%= link_to "24시간 최대상승코인 5개 찾기", homes_third_path %>

app/views/homes/second.html.erb
<h1>Homes#second</h1>
<p>Find me in app/views/homes/second.html.erb</p>

<div>
    <div> 코인명 / 현재가격 / 거래대금 </div>
    <hr>
    <%= @result %>
    <% @result.each do |cur| %>
        <% if cur[0] != "date" %>
            <%= cur[0] %> / 
            <%= cur[-1]["closing_price"] %> /
            <%= cur[-1]["acc_trade_value_24H"] %> /
            <%= cur[-1]["fluctate_rate_24H"] %> <br>
        <% end %>
    <% end %>
</div>

<hr>
<%= link_to "돌아가기", root_path %>

app/views/homes/third.html.erb
<h1>Homes#third</h1>
<p>Find me in app/views/homes/third.html.erb</p>

<%= @max_fluc %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>